name: location_ios
description: iOS implementation of the location plugin
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.4

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      ios:
        pluginClass: LocationPlugin
        dartPluginClass: LocationIOS

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^5.0.0-dev.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.0.7
  plugin_platform_interface: ^2.1.4
  very_good_analysis: ^4.0.0+1
